# Generated by Django 5.2.15 on 2026-08-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_financeprofile_billing_email_financeprofile_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeaccess',
            name='role',
            field=models.CharField(choices=[('finance', 'Finance'), ('collections', 'Collections')], default='finance', max_length=20),
        ),
    ]
